services:
  daily_weather:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daily_weather
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
    env_file: .env
    volumes:
      - ./data:/daily_weather/app/data
    command: sleep infinity 